/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phamagest;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TOYIFANE
 */
public class AjouterUser extends javax.swing.JFrame {

    private String emailFormat = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    private String phoneFormat = "^[0-9]*$";
    private int verifierUsername = 0;

    /**
     * Creates new form AjouterUser
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;

    public AjouterUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = Connect.getConnection();
        iconlb.setVisible(false);
        setLocationRelativeTo(null);
        effacer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPrenom = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboUser = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iconlb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ajouter User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 740, 10));

        txtPrenom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 230, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 230, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 230, -1));

        txtPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 230, -1));

        txtAdresse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 230, -1));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 230, -1));

        jLabel2.setText("Téléphone");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, -1));

        jLabel3.setText("Fonction");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, -1));

        jLabel4.setText("Prenom");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        jLabel7.setText("Username");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 110, -1));

        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 110, -1));

        jLabel9.setText("Adresse");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 110, -1));

        comboUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "pharmacien" }));
        getContentPane().add(comboUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 230, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/floppy-disk.png"))); // NOI18N
        jButton1.setText("Enregister");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 20, 20));

        iconlb.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        iconlb.setText("jLabel10");
        getContentPane().add(iconlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        String username = txtUsername.getText();
        if (!username.equals("")) {
            iconlb.setVisible(true);
            iconlb.setIcon(new ImageIcon("src\\images\\yes.png"));
            iconlb.setText("");
            verifierUsername = 0;
            try {
                con = Connect.getConnection();
                pst = con.prepareStatement("SELECT * FROM utilisateurs WHERE nom ='" + username + "'");
                res = pst.executeQuery();
                while (res.next()) {
                    verifierUsername = 1;
                    iconlb.setIcon(new ImageIcon("src\\images\\close.png"));
                    iconlb.setText("");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {
            iconlb.setVisible(false);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fonction = (String) comboUser.getSelectedItem();
        String prenom = txtPrenom.getText();

        String phone = txtPhone.getText();
        String adresse = txtAdresse.getText();
        String email = txtEmail.getText();
        String password = txtPass.getText();
        String username = txtUsername.getText();

        if (prenom.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ prénom est vide");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ email est vide");
        } else if (!email.matches(emailFormat)) {
            JOptionPane.showMessageDialog(null, "L'email est invalide");
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ username est vide");
        } else if (verifierUsername == 1) {
            JOptionPane.showMessageDialog(null, "Ce nom existe déjà");
        } else if (adresse.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ adresse est vide");
        } else if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ Téléphone est vide");
        } else if (!phone.matches(phoneFormat) || phone.length() != 10) {
            JOptionPane.showMessageDialog(null, "Le numéro de téléphone est invalide");
        } else if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ Téléphone est vide");
        } else if (!phone.matches(phoneFormat) || phone.length() != 10) {
            JOptionPane.showMessageDialog(null, "Le numéro de téléphone est invalide");
        } else {
            try {
                con = Connect.getConnection();
                pst = con.prepareStatement("INSERT INTO utilisateurs (nom,prenom,telephone,email,fonction,adresse,pass) VALUES (?,?,?,?,?,?,?)");
                pst.setString(1, username);
                pst.setString(2, prenom);
                pst.setString(3, phone);
                pst.setString(4, email);
                pst.setString(5, fonction);
                pst.setString(6, adresse);
                pst.setString(7, password);
                res = pst.executeQuery();
                JOptionPane.showMessageDialog(null, "Un nouveau admin a été inséré ", "avec succès", 1);
                setVisible(false);
                new AjouterUser().setVisible(true);
                effacer();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Un nouveau admin a été inséré");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JLabel iconlb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public void effacer() {
        txtEmail.setText("");
        txtPass.setText("");
        txtPhone.setText("");
        txtPrenom.setText("");
        txtUsername.setText("");
        comboUser.setSelectedIndex(0);
    }
}
